#배열 기본 연산

배열과 스칼라와의 연산

In [1]:
import numpy as np

In [2]:
a=np.arange(3)
a

array([0, 1, 2])

In [3]:
print(a+2)
print(a-2)
print(a*2)
print(a/2)

[2 3 4]
[-2 -1  0]
[0 2 4]
[0.  0.5 1. ]


#배열과 배열의 연산

In [5]:
a=np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
b=np.full_like(a,[1,2,3])
b

array([[1, 2, 3],
       [1, 2, 3]])

In [8]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[2 4 6]
 [5 7 9]]
[[0 0 0]
 [3 3 3]]
[[ 1  4  9]
 [ 4 10 18]]
[[1.  1.  1. ]
 [4.  2.5 2. ]]


In [9]:
a=np.arange(4)
a

array([0, 1, 2, 3])

In [11]:
b=np.arange(0.5,4,1)
b

array([0.5, 1.5, 2.5, 3.5])

In [12]:
a+=b

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [13]:
b+=a
b

array([0.5, 2.5, 4.5, 6.5])

In [14]:
a=np.full((2,3),[1,2,3])
a

array([[1, 2, 3],
       [1, 2, 3]])

In [15]:
b=np.full((3,2),[2,1])
b

array([[2, 1],
       [2, 1],
       [2, 1]])

In [16]:
a@b

array([[12,  6],
       [12,  6]])

In [17]:
a.dot(b)

array([[12,  6],
       [12,  6]])

In [18]:
b.dot(a)

array([[3, 6, 9],
       [3, 6, 9],
       [3, 6, 9]])

#배열 함수와 범용함수

배열함수

In [20]:
a=np.array([[10,20],[5,8],[1,2]])
a

array([[10, 20],
       [ 5,  8],
       [ 1,  2]])

In [21]:
a.sum()

46

In [22]:
a.sum(axis=0)

array([16, 30])

In [23]:
a.sum(axis=1)

array([30, 13,  3])

In [25]:
print(np.sum(a))
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))

46
[16 30]
[30 13  3]


In [27]:
a=np.array([[3,5,8],[1,2,3]])
a

array([[3, 5, 8],
       [1, 2, 3]])

In [29]:
a.cumsum()

array([ 3,  8, 16, 17, 19, 22])

In [30]:
a.cumsum(axis=0)

array([[ 3,  8, 16],
       [ 1,  3,  6]])

In [31]:
a.cumsum(axis=1)

array([[ 3,  8, 16],
       [ 1,  3,  6]])

#범용함수

In [32]:
a=np.array([1,4,9])
np.sqrt(a)

array([1., 2., 3.])

In [33]:
np.log(a)

array([0.        , 1.38629436, 2.19722458])

In [34]:
a=np.array([1,4,9])
a

array([1, 4, 9])

In [35]:
b=np.full_like(a,2)
b

array([2, 2, 2])

In [36]:
np.add(a,b)

array([ 3,  6, 11])

In [37]:
np.divide(a,b)

array([0.5, 2. , 4.5])

In [38]:
np.power(a,b)

array([ 1, 16, 81])